-- ============================================================
-- SCRIPT DDL - MODELO OLAP COM DUAS FATOS (ORACLE DATABASE)
-- ============================================================

-- 1. TABELAS DE DIMENSÃO

CREATE TABLE DIM_PRODUTO (
    ID_PRODUTO NUMBER,
    CATEGORIA  NUMBER,
    VALOR      NUMBER(15, 2),
    CONSTRAINT PK_DIM_PRODUTO PRIMARY KEY (ID_PRODUTO)
);

CREATE TABLE DIM_TEMPO (
    ID_DATA      NUMBER,
    ANO          NUMBER(4),
    QUADRIMESTRE NUMBER(1),
    CONSTRAINT PK_DIM_TEMPO PRIMARY KEY (ID_DATA)
);

CREATE TABLE DIM_CLIENTE (
    ID_CLIENTE   NUMBER,
    ESTADO_CIVIL NUMBER,
    CONSTRAINT PK_DIM_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE DIM_FILIAL (
    ID_FILIAL NUMBER,
    NOME      VARCHAR2(100),
    CIDADE    VARCHAR2(100),
    CONSTRAINT PK_DIM_FILIAL PRIMARY KEY (ID_FILIAL)
);

-- 2. TABELAS FATO

-- 2.1. Fato Venda
CREATE TABLE FATO_VENDA (
    ID_VENDA   NUMBER,
    ID_PRODUTO NUMBER NOT NULL,
    ID_DATA    NUMBER NOT NULL,
    ID_CLIENTE NUMBER NOT NULL,
    ID_FILIAL  NUMBER NOT NULL,
    QUANTIDADE NUMBER,
    VALOR      NUMBER(15, 2),
    
    CONSTRAINT PK_FATO_VENDA PRIMARY KEY (ID_VENDA),
    CONSTRAINT FK_FATO_VENDA_DIM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES DIM_PRODUTO (ID_PRODUTO),
    CONSTRAINT FK_FATO_VENDA_DIM_TEMPO   FOREIGN KEY (ID_DATA)    REFERENCES DIM_TEMPO (ID_DATA),
    CONSTRAINT FK_FATO_VENDA_DIM_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE (ID_CLIENTE),
    CONSTRAINT FK_FATO_VENDA_DIM_FILIAL  FOREIGN KEY (ID_FILIAL)  REFERENCES DIM_FILIAL (ID_FILIAL)
);

-- 2.2. Fato Concorrente
CREATE TABLE FATO_CONCORRENTE (
    ID_CONCORRENTE NUMBER,
    ID_DATA        NUMBER NOT NULL,
    ANO            NUMBER(4),
    MES            NUMBER(2),
    DESCRICAO      VARCHAR2(100),
    
    CONSTRAINT PK_FATO_CONCORRENTE PRIMARY KEY (ID_CONCORRENTE),
    CONSTRAINT FK_FATO_CONCORRENTE_DIM_TEMPO FOREIGN KEY (ID_DATA) REFERENCES DIM_TEMPO (ID_DATA)
);

-- 3. ÍNDICES DE PERFORMANCE PARA CONSULTAS (OLAP)

-- Índices para FATO_Venda
CREATE INDEX IX_FATO_VENDA_PRODUTO ON FATO_VENDA(ID_PRODUTO);
CREATE INDEX IX_FATO_VENDA_TEMPO   ON FATO_VENDA(ID_DATA);
CREATE INDEX IX_FATO_VENDA_CLIENTE ON FATO_VENDA(ID_CLIENTE);
CREATE INDEX IX_FATO_VENDA_FILIAL  ON FATO_VENDA(ID_FILIAL);

-- Índice para FATO_Concorrente
CREATE INDEX IX_FATO_CONCORRENTE_TEMPO ON FATO_CONCORRENTE(ID_DATA);